# Generated by Django 4.1 on 2022-08-25 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hijo",
            name="placa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Usuarios.carro",
            ),
        ),
    ]
