# Generated by Django 4.1 on 2022-08-22 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Usuarios", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hijo", old_name="apellido", new_name="apellidos",
        ),
    ]
