# Generated by Django 4.1 on 2022-08-26 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Usuarios", "0002_alter_hijo_placa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hijo",
            name="posicion",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Posicion del hijo"
            ),
        ),
    ]
