# Generated by Django 4.1 on 2022-08-22 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Usuarios", "0002_rename_apellido_hijo_apellidos"),
    ]

    operations = [
        migrations.CreateModel(
            name="Carros",
            fields=[
                (
                    "placa",
                    models.CharField(
                        max_length=10, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "nombre_conductor",
                    models.CharField(
                        max_length=150, verbose_name="Nombre del conductor"
                    ),
                ),
                ("Marca", models.CharField(max_length=50)),
                ("color", models.CharField(max_length=20)),
                (
                    "telefono_conductor",
                    models.CharField(
                        max_length=10,
                        unique=True,
                        verbose_name="Teléfono del conductor",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="hijo",
            name="placa",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Usuarios.carros",
            ),
        ),
    ]
