# Generated by Django 4.1 on 2022-08-22 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Usuarios", "0003_carros_alter_hijo_placa"),
    ]

    operations = [
        migrations.AddField(
            model_name="carros",
            name="estado",
            field=models.BooleanField(default=True, verbose_name="Estado del carro"),
        ),
    ]
