# Generated by Django 4.1 on 2022-08-23 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Usuarios", "0004_carros_estado"),
    ]

    operations = [
        migrations.RenameModel(old_name="Carros", new_name="Carro",),
    ]
