# Generated by Django 4.1 on 2022-08-23 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Usuarios", "0005_rename_carros_carro"),
    ]

    operations = [
        migrations.AlterModelTable(name="carro", table="carros",),
    ]
